#!/bin/sh

# Name: Install
# Purpose: install script for the femover product

# remember the top-level directory

cd `dirname $0`
TOP=`pwd`

# if no Configuration file, bail out

if [ ! -f "${TOP}/Configuration" ]; then
        echo "Missing Configuration file"
        exit 1
fi

# source the Configuration file

. "${TOP}/Configuration"

mkdir -p $VLAD_DATA
mkdir -p $VLAD_OUTPUT
mkdir -p $VLAD_TMP

$PYTHON ${VLAD}/bin/installer.py ${VLAD}/vlad.cfg

ln -s ${VLAD_OUTPUT} ${VLAD_BUILD}/output
